/* tslint:disable */
/* eslint-disable */
/**
 * StudyWithMe API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface DtoLoginRequest {
    'email'?: string;
    'password'?: string;
    'username'?: string;
}
export interface DtoLoginResponse {
    'accessToken'?: string;
    'expiresIn'?: string;
    'tokenType'?: string;
    'user'?: DtoUserResponse;
}
export interface DtoSignUpUserRequest {
    'email'?: string;
    'firstname'?: string;
    'lastname'?: string;
    'password'?: string;
    'topicsOfInterest'?: Array<ModelTopicOfInterest>;
    'username'?: string;
}
export interface DtoSignUpUserResponse {
    'firstname'?: string;
    'lastname'?: string;
    'username'?: string;
}
export interface DtoTeamRequest {
    'description'?: string;
    'ispublic'?: boolean;
    'name'?: string;
    'teamtopic'?: ModelTopicOfInterest;
    'userid'?: string;
}


export interface DtoUpdateStatisticsRequest {
    'teamId'?: string;
    'timeSpentOnApp'?: number;
    'timeSpentOnTeam'?: number;
}
export interface DtoUpdateStatisticsResponse {
    'timeSpentOnTeams'?: Array<ModelTimeSpentOnTeam>;
    'totalTimeSpentOnApp'?: number;
    'userId'?: string;
}
export interface DtoUserResponse {
    'email'?: string;
    'firstname'?: string;
    'id'?: string;
    'lastname'?: string;
    'statistics'?: ModelStatistics;
    'teams'?: Array<string>;
    'topicsOfInterest'?: Array<ModelTopicOfInterest>;
    'username'?: string;
}
export interface DtoUserToTeamRequest {
    'teamId': string;
    'userId': string;
}
export interface EntityTeam {
    'description'?: string;
    'id'?: string;
    'ispublic'?: boolean;
    'name'?: string;
    'teamtopic'?: ModelTopicOfInterest;
    'users'?: Array<string>;
}


export interface EntityUser {
    'email'?: string;
    'firstname'?: string;
    'id'?: string;
    'lastname'?: string;
    'password'?: string;
    'statistics'?: ModelStatistics;
    'teams'?: Array<string>;
    'topicsOfInterest'?: Array<ModelTopicOfInterest>;
    'username'?: string;
}
export interface ModelStatistics {
    'timeSpentOnTeams'?: Array<ModelTimeSpentOnTeam>;
    'totalTimeSpentOnApp'?: number;
}
export interface ModelTimeSpentOnTeam {
    'duration'?: number;
    'teamId'?: string;
}

export const ModelTopicOfInterest = {
    Mathematics: 'Mathematics',
    Science: 'Science',
    ComputerScience: 'ComputerScience',
    Programming: 'Programming',
    Art: 'Art',
    Music: 'Music',
    Photography: 'Photography',
    Language: 'Language'
} as const;

export type ModelTopicOfInterest = typeof ModelTopicOfInterest[keyof typeof ModelTopicOfInterest];



/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get teams - all teams, by name, or by prefix with limit
         * @summary Get teams with optional filtering
         * @param {string} [name] Filter by exact name
         * @param {string} [prefix] Filter by name prefix
         * @param {number} [limit] Limit results (required with prefix)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        teamsGet: async (name?: string, prefix?: string, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/teams`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }

            if (prefix !== undefined) {
                localVarQueryParameter['prefix'] = prefix;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete a team by providing team ID
         * @summary Delete a team
         * @param {string} id Team ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        teamsIdDelete: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('teamsIdDelete', 'id', id)
            const localVarPath = `/teams/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get team details by ID
         * @summary Get a team by ID
         * @param {string} id Team ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        teamsIdGet: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('teamsIdGet', 'id', id)
            const localVarPath = `/teams/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update team details by providing team ID and updated details
         * @summary Update a team
         * @param {string} id Team ID
         * @param {EntityTeam} team Updated team details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        teamsIdPut: async (id: string, team: EntityTeam, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('teamsIdPut', 'id', id)
            // verify required parameter 'team' is not null or undefined
            assertParamExists('teamsIdPut', 'team', team)
            const localVarPath = `/teams/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(team, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create a new team with the provided details
         * @summary Create a new team
         * @param {DtoTeamRequest} request Team details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        teamsPost: async (request: DtoTeamRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('teamsPost', 'request', request)
            const localVarPath = `/teams`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete a user from a team by providing team ID
         * @summary Delete a user from a team
         * @param {DtoUserToTeamRequest} request User ID and Team ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        teamsUsersDelete: async (request: DtoUserToTeamRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('teamsUsersDelete', 'request', request)
            const localVarPath = `/teams/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Add a user to a team by providing user ID and team ID
         * @summary Add a user to a team
         * @param {DtoUserToTeamRequest} request User ID and Team ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        teamsUsersPut: async (request: DtoUserToTeamRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('teamsUsersPut', 'request', request)
            const localVarPath = `/teams/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all users
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a user
         * @param {string} id The user\&#39;s ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersIdDelete: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('usersIdDelete', 'id', id)
            const localVarPath = `/users/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a user by ID
         * @param {string} id The user\&#39;s ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersIdGet: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('usersIdGet', 'id', id)
            const localVarPath = `/users/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a user
         * @param {string} id The user\&#39;s ID
         * @param {EntityUser} user The updated user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersIdPut: async (id: string, user: EntityUser, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('usersIdPut', 'id', id)
            // verify required parameter 'user' is not null or undefined
            assertParamExists('usersIdPut', 'user', user)
            const localVarPath = `/users/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(user, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update user statistics
         * @param {string} id The user\&#39;s ID
         * @param {DtoUpdateStatisticsRequest} request The statistics update request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersIdStatisticsPut: async (id: string, request: DtoUpdateStatisticsRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('usersIdStatisticsPut', 'id', id)
            // verify required parameter 'request' is not null or undefined
            assertParamExists('usersIdStatisticsPut', 'request', request)
            const localVarPath = `/users/{id}/statistics`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Accepts either `email` or `username` along with `password`. Returns an access token and the full user (without password).
         * @summary Login user by email or username and return JWT
         * @param {DtoLoginRequest} request The login request (email or username + password)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersLoginPost: async (request: DtoLoginRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('usersLoginPost', 'request', request)
            const localVarPath = `/users/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Register a new user
         * @param {DtoSignUpUserRequest} request The sign-up request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersSignupPost: async (request: DtoSignUpUserRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('usersSignupPost', 'request', request)
            const localVarPath = `/users/signup`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Join voice chat room
         * @param {string} teamId Team ID
         * @param {string} userId User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        voiceTeamIdGet: async (teamId: string, userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'teamId' is not null or undefined
            assertParamExists('voiceTeamIdGet', 'teamId', teamId)
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('voiceTeamIdGet', 'userId', userId)
            const localVarPath = `/voice/{teamId}`
                .replace(`{${"teamId"}}`, encodeURIComponent(String(teamId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (userId !== undefined) {
                localVarQueryParameter['userId'] = userId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Leave voice chat room
         * @param {string} teamId Team ID
         * @param {string} userId User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        voiceTeamIdLeaveDelete: async (teamId: string, userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'teamId' is not null or undefined
            assertParamExists('voiceTeamIdLeaveDelete', 'teamId', teamId)
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('voiceTeamIdLeaveDelete', 'userId', userId)
            const localVarPath = `/voice/{teamId}/leave`
                .replace(`{${"teamId"}}`, encodeURIComponent(String(teamId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (userId !== undefined) {
                localVarQueryParameter['userId'] = userId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * Get teams - all teams, by name, or by prefix with limit
         * @summary Get teams with optional filtering
         * @param {string} [name] Filter by exact name
         * @param {string} [prefix] Filter by name prefix
         * @param {number} [limit] Limit results (required with prefix)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async teamsGet(name?: string, prefix?: string, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<EntityTeam>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.teamsGet(name, prefix, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.teamsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Delete a team by providing team ID
         * @summary Delete a team
         * @param {string} id Team ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async teamsIdDelete(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.teamsIdDelete(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.teamsIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get team details by ID
         * @summary Get a team by ID
         * @param {string} id Team ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async teamsIdGet(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EntityTeam>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.teamsIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.teamsIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update team details by providing team ID and updated details
         * @summary Update a team
         * @param {string} id Team ID
         * @param {EntityTeam} team Updated team details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async teamsIdPut(id: string, team: EntityTeam, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EntityTeam>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.teamsIdPut(id, team, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.teamsIdPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Create a new team with the provided details
         * @summary Create a new team
         * @param {DtoTeamRequest} request Team details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async teamsPost(request: DtoTeamRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EntityTeam>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.teamsPost(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.teamsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Delete a user from a team by providing team ID
         * @summary Delete a user from a team
         * @param {DtoUserToTeamRequest} request User ID and Team ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async teamsUsersDelete(request: DtoUserToTeamRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.teamsUsersDelete(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.teamsUsersDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Add a user to a team by providing user ID and team ID
         * @summary Add a user to a team
         * @param {DtoUserToTeamRequest} request User ID and Team ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async teamsUsersPut(request: DtoUserToTeamRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.teamsUsersPut(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.teamsUsersPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all users
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<EntityUser>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.usersGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a user
         * @param {string} id The user\&#39;s ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersIdDelete(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: string; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersIdDelete(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.usersIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a user by ID
         * @param {string} id The user\&#39;s ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersIdGet(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EntityUser>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.usersIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a user
         * @param {string} id The user\&#39;s ID
         * @param {EntityUser} user The updated user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersIdPut(id: string, user: EntityUser, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EntityUser>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersIdPut(id, user, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.usersIdPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update user statistics
         * @param {string} id The user\&#39;s ID
         * @param {DtoUpdateStatisticsRequest} request The statistics update request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersIdStatisticsPut(id: string, request: DtoUpdateStatisticsRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DtoUpdateStatisticsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersIdStatisticsPut(id, request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.usersIdStatisticsPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Accepts either `email` or `username` along with `password`. Returns an access token and the full user (without password).
         * @summary Login user by email or username and return JWT
         * @param {DtoLoginRequest} request The login request (email or username + password)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersLoginPost(request: DtoLoginRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DtoLoginResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersLoginPost(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.usersLoginPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Register a new user
         * @param {DtoSignUpUserRequest} request The sign-up request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersSignupPost(request: DtoSignUpUserRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DtoSignUpUserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersSignupPost(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.usersSignupPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Join voice chat room
         * @param {string} teamId Team ID
         * @param {string} userId User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async voiceTeamIdGet(teamId: string, userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.voiceTeamIdGet(teamId, userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.voiceTeamIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Leave voice chat room
         * @param {string} teamId Team ID
         * @param {string} userId User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async voiceTeamIdLeaveDelete(teamId: string, userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: string; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.voiceTeamIdLeaveDelete(teamId, userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.voiceTeamIdLeaveDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * Get teams - all teams, by name, or by prefix with limit
         * @summary Get teams with optional filtering
         * @param {string} [name] Filter by exact name
         * @param {string} [prefix] Filter by name prefix
         * @param {number} [limit] Limit results (required with prefix)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        teamsGet(name?: string, prefix?: string, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<EntityTeam>> {
            return localVarFp.teamsGet(name, prefix, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete a team by providing team ID
         * @summary Delete a team
         * @param {string} id Team ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        teamsIdDelete(id: string, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.teamsIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Get team details by ID
         * @summary Get a team by ID
         * @param {string} id Team ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        teamsIdGet(id: string, options?: RawAxiosRequestConfig): AxiosPromise<EntityTeam> {
            return localVarFp.teamsIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Update team details by providing team ID and updated details
         * @summary Update a team
         * @param {string} id Team ID
         * @param {EntityTeam} team Updated team details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        teamsIdPut(id: string, team: EntityTeam, options?: RawAxiosRequestConfig): AxiosPromise<EntityTeam> {
            return localVarFp.teamsIdPut(id, team, options).then((request) => request(axios, basePath));
        },
        /**
         * Create a new team with the provided details
         * @summary Create a new team
         * @param {DtoTeamRequest} request Team details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        teamsPost(request: DtoTeamRequest, options?: RawAxiosRequestConfig): AxiosPromise<EntityTeam> {
            return localVarFp.teamsPost(request, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete a user from a team by providing team ID
         * @summary Delete a user from a team
         * @param {DtoUserToTeamRequest} request User ID and Team ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        teamsUsersDelete(request: DtoUserToTeamRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.teamsUsersDelete(request, options).then((request) => request(axios, basePath));
        },
        /**
         * Add a user to a team by providing user ID and team ID
         * @summary Add a user to a team
         * @param {DtoUserToTeamRequest} request User ID and Team ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        teamsUsersPut(request: DtoUserToTeamRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.teamsUsersPut(request, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all users
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<EntityUser>> {
            return localVarFp.usersGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a user
         * @param {string} id The user\&#39;s ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersIdDelete(id: string, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: string; }> {
            return localVarFp.usersIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a user by ID
         * @param {string} id The user\&#39;s ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersIdGet(id: string, options?: RawAxiosRequestConfig): AxiosPromise<EntityUser> {
            return localVarFp.usersIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a user
         * @param {string} id The user\&#39;s ID
         * @param {EntityUser} user The updated user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersIdPut(id: string, user: EntityUser, options?: RawAxiosRequestConfig): AxiosPromise<EntityUser> {
            return localVarFp.usersIdPut(id, user, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update user statistics
         * @param {string} id The user\&#39;s ID
         * @param {DtoUpdateStatisticsRequest} request The statistics update request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersIdStatisticsPut(id: string, request: DtoUpdateStatisticsRequest, options?: RawAxiosRequestConfig): AxiosPromise<DtoUpdateStatisticsResponse> {
            return localVarFp.usersIdStatisticsPut(id, request, options).then((request) => request(axios, basePath));
        },
        /**
         * Accepts either `email` or `username` along with `password`. Returns an access token and the full user (without password).
         * @summary Login user by email or username and return JWT
         * @param {DtoLoginRequest} request The login request (email or username + password)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersLoginPost(request: DtoLoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<DtoLoginResponse> {
            return localVarFp.usersLoginPost(request, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Register a new user
         * @param {DtoSignUpUserRequest} request The sign-up request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersSignupPost(request: DtoSignUpUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<DtoSignUpUserResponse> {
            return localVarFp.usersSignupPost(request, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Join voice chat room
         * @param {string} teamId Team ID
         * @param {string} userId User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        voiceTeamIdGet(teamId: string, userId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.voiceTeamIdGet(teamId, userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Leave voice chat room
         * @param {string} teamId Team ID
         * @param {string} userId User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        voiceTeamIdLeaveDelete(teamId: string, userId: string, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: string; }> {
            return localVarFp.voiceTeamIdLeaveDelete(teamId, userId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /**
     * Get teams - all teams, by name, or by prefix with limit
     * @summary Get teams with optional filtering
     * @param {string} [name] Filter by exact name
     * @param {string} [prefix] Filter by name prefix
     * @param {number} [limit] Limit results (required with prefix)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public teamsGet(name?: string, prefix?: string, limit?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).teamsGet(name, prefix, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete a team by providing team ID
     * @summary Delete a team
     * @param {string} id Team ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public teamsIdDelete(id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).teamsIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get team details by ID
     * @summary Get a team by ID
     * @param {string} id Team ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public teamsIdGet(id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).teamsIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update team details by providing team ID and updated details
     * @summary Update a team
     * @param {string} id Team ID
     * @param {EntityTeam} team Updated team details
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public teamsIdPut(id: string, team: EntityTeam, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).teamsIdPut(id, team, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create a new team with the provided details
     * @summary Create a new team
     * @param {DtoTeamRequest} request Team details
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public teamsPost(request: DtoTeamRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).teamsPost(request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete a user from a team by providing team ID
     * @summary Delete a user from a team
     * @param {DtoUserToTeamRequest} request User ID and Team ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public teamsUsersDelete(request: DtoUserToTeamRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).teamsUsersDelete(request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Add a user to a team by providing user ID and team ID
     * @summary Add a user to a team
     * @param {DtoUserToTeamRequest} request User ID and Team ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public teamsUsersPut(request: DtoUserToTeamRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).teamsUsersPut(request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all users
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).usersGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a user
     * @param {string} id The user\&#39;s ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersIdDelete(id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).usersIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a user by ID
     * @param {string} id The user\&#39;s ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersIdGet(id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).usersIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a user
     * @param {string} id The user\&#39;s ID
     * @param {EntityUser} user The updated user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersIdPut(id: string, user: EntityUser, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).usersIdPut(id, user, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update user statistics
     * @param {string} id The user\&#39;s ID
     * @param {DtoUpdateStatisticsRequest} request The statistics update request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersIdStatisticsPut(id: string, request: DtoUpdateStatisticsRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).usersIdStatisticsPut(id, request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Accepts either `email` or `username` along with `password`. Returns an access token and the full user (without password).
     * @summary Login user by email or username and return JWT
     * @param {DtoLoginRequest} request The login request (email or username + password)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersLoginPost(request: DtoLoginRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).usersLoginPost(request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Register a new user
     * @param {DtoSignUpUserRequest} request The sign-up request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersSignupPost(request: DtoSignUpUserRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).usersSignupPost(request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Join voice chat room
     * @param {string} teamId Team ID
     * @param {string} userId User ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public voiceTeamIdGet(teamId: string, userId: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).voiceTeamIdGet(teamId, userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Leave voice chat room
     * @param {string} teamId Team ID
     * @param {string} userId User ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public voiceTeamIdLeaveDelete(teamId: string, userId: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).voiceTeamIdLeaveDelete(teamId, userId, options).then((request) => request(this.axios, this.basePath));
    }
}



